/*

You are given two strings, s and t which only consist of lowercase letters. t is generated by shuffling the letters in s as well as potentially adding an additional random character. Return the letter that was randomly added to t if it exists, otherwise, return ’  ‘.
Note: You may assume that at most one additional character can be added to t.

*/

const spotTheDifference = (s,t) =>{
    var tracedChars = new Map();
    
    for (let index = 0; index < s.length; index++) {
        const element = s[index];
        if(tracedChars.has(element)){
            tracedChars.set(element, tracedChars.get(element)+1);
        }else{
            tracedChars.set(element, 1);
        }
    }

    for (let index = 0; index < t.length; index++) {
        const element = t[index];

        if(tracedChars.has(element)){
            if(tracedChars.get(element) > 1){
                tracedChars.set(element, tracedChars.get(element)-1);
            }else{
                tracedChars.delete(element);
            }
        }else{
            return element;
        }
    }

    if(tracedChars.size>0){
        return tracedChars.keys().next().value;
    }else{
        return "";
    }
}

const s = "coding";
const t = "ingcod";
const differenceChar = spotTheDifference(s, t);
console.log(` Difference in '${s}' and '${t}': ${differenceChar}.`);